### ISSUE TITLE
Fatal error occured: Wrong structure

### ISSUE THREAD

**Issue by mbnn** [spotweb/spotweb#153]
Since updating to latest PHP/SQL, Spotweb works but I keep getting:
Fatal error occured retrieving reports:
  HY000: 1682: Native table 'performance_schema'.'session_variables' has the wrong structure

SpotWeb v0.67.28.31 on PHP v5.6.17-3ubuntu1 crashed object(SqlErrorException)#25 (8) { ["message":protected]=> string(90) "HY000: 1682: Native table 'performance_schema'.'session_variables' has the wrong structure"

Any idea? :)

**Comment by mesa57** [comment]
That table does not belong to spotweb, but to mysql.
Clearly there is something wrong with you're mysql installation. 
Within mysql workbench you could try to disable performance counting, but of course, that won't solve the root cause.

Read also this
http://stackoverflow.com/questions/6288103/native-table-performance-schema-has-the-wrong-structure
and this
https://dev.mysql.com/doc/refman/5.5/en/performance-schema-build-configuration.html

**Comment by mbnn** [comment]
You are right :) Thx, i fixed this by using:

- mysql_upgrade --upgrade-system-tables --force -u root -p
- Restart mysql (service mysql restart)

All fixed :)

**Comment by mesa57** [comment]
Thanks for reporting back :smiley:
