### ISSUE TITLE
Introduce Slack or Gitter for development

### ISSUE THREAD

**Issue by mbirth** [spotweb/spotweb#206]
While this issue list works for tracking problems and their fixes, it's too slow for several people working on the same problem sometimes. For that, I'd suggest a [Slack](https://slack.com/) or [Gitter](https://gitter.im/) channel. This way, you could avoid having two or three people working on the same problem asynchronously. Also, it can be connected to a CI tool like Scrutinizer or Travis and all people will get notified of any new problems.

**Comment by mesa57** [comment]
There is alread a spotweb.slack.com
Who is that ?

**Comment by mbirth** [comment]
When trying to sign up for that Slack space, it says: "If you have an @spot-web.jp email address, you can create an account.".

So it's from these guys: http://spot-web.jp/ … looks like you have to come up with something slightly different.

**Comment by mesa57** [comment]
pfff, spotweb2.slack.com

**Comment by mbirth** [comment]
So, could you invite me to the team, please? slack(dot)com(at)birth(minus)online(dot)de

**Comment by dsadsdadsadsadsds** [comment]
I don't like that you moved discussion of an opensource project to a closed / private chat.

**Comment by mesa57** [comment]
It is more to facilitate discussions without have to relate to issue's. Anyhow, I have hardly used it until now.

**Comment by dsadsdadsadsadsds** [comment]
Well, it's up to you guys -- but the whole idea of open source is that you have the development in the open. Development is (much) more than just typing in code, Github issues are a good way to preserve history and to come to an general agreement on how things are done.

anyways - it's up to you as long as you don't start making references to 'as discussed on slack' because that would suck :wink:

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds That's probably why the idea isn't succesfull and we're still spamming here :stuck_out_tongue:
