### ISSUE TITLE
GUI gives X through NZB, but NZB is downloaded and pushed

### ISSUE THREAD

**Issue by aroundmyroom** [spotweb/spotweb#236]
![image](https://cloud.githubusercontent.com/assets/250108/20554657/b021a208-b15d-11e6-849a-4d4a63ee3592.png)

valid NZB's sent to sabnzbd but also NZB's with a X but also these are sent fine to sabnzbdplus

It seems related to this:

[Wed Nov 23 09:15:49.348088 2016] [:error] [pid 10443] [client 10.10.10.101:50443] sabnzbd push : http returncode: 700 / Operation timed out after 15001 milliseconds with 0 bytes received / , referer: http://spotweb.mydomainsomewhere.io/?page=index&search[tree]=&search[value][]=SpotterID:=:DEF:1Pgosw&sortby=date&sortdir=desc

**Comment by mesa57** [comment]
Which sabnzbd version are you using ?

**Comment by Sweepr** [comment]
In spotweb/lib/services/NzbHandler/Services_NzbHandler_Pushsabnzbd.php on line 2 it reads:

`define("SABNZBD_TIMEOUT",15);`

Which is a weird setting, because the variable is not used anywhere else in the code.

By reproducing the issue i noticed that if a push last's longer then 15 second's a timeout get's thrown and spotweb thinks the transfer failed, while infact the NZB got picked up by SabNZBd, but it didn't get the time to properly respond within the set timeframe of 15 second's

**Comment by aroundmyroom** [comment]
although the timeout is set to 15 and the spot is even sent after that time I have fixed my issue.
my timeout was caused due to incorrect settings causing my server(s) to be ver slow.
Fso for me this 'bug' can be removed. No need to investigate or fix (or if you want to fix at a low priority)

**Comment by Sweepr** [comment]
Alright, feel free to re-open if needed

**Comment by Sweepr** [comment]
CURLOPT_TIMEOUT set to low which on slower system's or networks can cause this error: "http returncode: 700 / Operation timed out after 15000 milliseconds with 0 bytes received / " as seen in this issue: #236

Increased TIMEOUT from 15 to 60 seconds to give the destination descent amount of time to respond to the source when slow.

Solved in: 9a8cbde
