### ISSUE TITLE
NZB handling error with mobile template

### ISSUE THREAD

**Issue by B-V-** [spotweb/spotweb#37]
I tried to use the mobile template for Phone and Tablet but failed with an error.
Changed some Spotweb settings as mentioned here:
https://github.com/Spotweb/Spotweb/wiki/Frequently-asked-questions#how-to-configure-a-new-kind-of-template--theme 

The template works fine, but when saving the NZB the page keeps loading and an error was logged:
FastCGI: server "/php-fpm-handler" stderr: PHP message: PHP Fatal error:  require(): Failed opening required 'lib/page/SpotPage_getnzbmobile.php' (include_path='.') in /volume1/web/spotweb/lib/SpotClassAutoload.php on line 20, 

The file 'lib/page/SpotPage_getnzbmobile.php' does not exists in this repository but does in the repository of h4rdc0m (4 years old, no longer active): 
https://github.com/h4rdc0m/spotweb/blob/master/lib/page/SpotPage_getnzbmobile.php  

| pulled that file but now get this error:
FastCGI: server "/php-fpm-handler" stderr: PHP message: PHP Catchable fatal error:  Argument 1 passed to SpotPage_getnzbmobile::__construct() must be an instance of SpotDb, instance of Dao_Mysql_Factory given, called in /volume1/web/spotweb/index.php on line 143 and defined in /volume1/web/spotweb/lib/page/SpotPage_getnzbmobile.php on line 6

Is it possible to use the mobile template with working NZB? 
What am I doing wrong?

**Comment by ckruijntjens** [comment]
Hi i have the same issue. i would like to see this issue resolved to. this issue is a long time in spotweb.

**Comment by Sweepr** [comment]
Temporary fix:

https://github.com/Sweepr/Spotweb-1/commit/512c67f84c20a9b165f1eff94bc5d1b9c8faa793

Still working on this issue as it's been bothering me for age's

**Comment by Sweepr** [comment]
For android users, they might be interested in this as a replacement for the mobile template:

https://play.google.com/store/apps/details?id=akerssies.dev.spotweb_control&hl=en

**Comment by B-V-** [comment]
Thanx for the tip spotwebcontrol. Works but is not bug free.
Keep up the good work!

**Comment by ckruijntjens** [comment]
thanx,

i will be verry happy when this issue is resolved :):)

**Comment by ckruijntjens** [comment]
Hello sweepr Any progrese made on the mobile template?

You are the boss if you van fix the mobile template!

**Comment by Sweepr** [comment]
@ckruijntjens

Still working on it, but don't expect anything in the coming weeks because i can only spend a few hours a day on this and it's alot more complicated than i expected, but don't worry.

Anyway, i'm currently using NZB360 Premium + https://github.com/Sweepr/Spotweb-1/commit/512c67f84c20a9b165f1eff94bc5d1b9c8faa793 and send the " manually downloaded" NZB directly to SabNZBd from the mobile template which is working perfect, altough i can imagine not everybody is willing to pay 10 dollar for a premium version i'm doing whatever i can to make this work.

**Comment by ckruijntjens** [comment]
Hi sweepr 

Thanx for the info i am sorry that i cant help. If i knew something of php i would be glad to help.

Thanx for trying to fix the issue.

Chris kruijntjens

Verstuurd vanaf mijn iPhone

**Comment by Sweepr** [comment]
@ckruijntjens 

Trying to open the download of the NZB in the same window was causing the loading issue, as this is not possible on mobile platform target="_blank" title='' needed to be added to the line of code.

After adding target="_blank" title=''

<tr><th> NZB: </th> <td> <a href='<?php echo $setpath; ?>?page=getnzb&amp;messageid=<?php echo $spot['messageid']; ?>' target="_blank" title=''>Download NZB</a> </td> </tr>

The code is working as supposed expect for the missing ( target="_blank" title='' )

As for now it is not yet possbile to automaticly push the *.nzb from mobile template to SabNZBd because you need special user permissions for that.

I'm looking at the option of logging in and logging out so one could use their own settings and push to SabNZBd based on those, this could take a while..

**Comment by Sweepr** [comment]
After adding target="_blank" title=''

<tr><th> NZB: </th> <td> <a href='<?php echo $setpath; ?>?page=getnzb&amp;messageid=<?php echo $spot['messageid']; ?>' target="_blank" title=''>Download NZB</a> </td> </tr>

The code is working as supposed expect for the missing ( target="_blank" title='' )

As for now it is not yet possbile to automaticly push the *.nzb from mobile template to SabNZBd because you need special user permissions for that.

I'm looking at the option of logging in and logging out so one could use their own settings and push to SabNZBd based on those, this could take a while..

**Comment by ckruijntjens** [comment]
Hello Sweeper,

After doing a git pull and updated to the last version the issue is still there. Just to inform.

Chris kruijntjens.

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: maandag 2 maart 2015 22:45
Aan: Spotweb/Spotweb
CC: ckruijntjens
Onderwerp: Re: [Spotweb] NZB handling error with mobile template (#37)

After adding target="_blank" title=''

NZB:

**Comment by Sweepr** [comment]
@ckruijntjens 
Sorry about that, my bad, was a little late when i did the commit ;-)

**Comment by ckruijntjens** [comment]
Hello Sweepr,

I tested it in mobile template. Both options are not working?

Chris kruijntjens.

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: dinsdag 3 maart 2015 16:36
Aan: Spotweb/Spotweb
CC: ckruijntjens
Onderwerp: Re: [Spotweb] NZB handling error with mobile template (#37)

@ckruijntjens <https://github.com/ckruijntjens>  
Sorry about that, my bad, was a little late when i did the commit ;-)

**Comment by Sweepr** [comment]
That's strange.. are you still getting the same error?

**Comment by ckruijntjens** [comment]
No i dont get an error. I just get a loading circle and that’s it?

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: woensdag 4 maart 2015 13:16
Aan: Spotweb/Spotweb
CC: ckruijntjens
Onderwerp: Re: [Spotweb] NZB handling error with mobile template (#37)

That's strange.. are you still getting the same error?

**Comment by Sweepr** [comment]
Which branch?

Can you manually edit file

**Comment by ckruijntjens** [comment]
Hi the master branche?

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: woensdag 4 maart 2015 13:31
Aan: Spotweb/Spotweb
CC: ckruijntjens
Onderwerp: Re: [Spotweb] NZB handling error with mobile template (#37)

Which branch?

Can you manually edit file

**Comment by Sweepr** [comment]
https://github.com/Spotweb/Spotweb/blob/master/templates/mobile/spotinfo.inc.php

That's weird, if i look here at line 18 and 52, the change's exist.


Line 18:  <a class="nzb" href="<?php echo $setpath ?>index.php?page=getnzb&amp;messageid=<?php echo $spot['messageid']; ?>" target="_blank" title='' data-transition='fade' data-icon="plus" data-rel="dialog" class="ui-btn-right">NZB</a>


Line 52:  <tr><th> NZB: </th> <td> <a href='<?php echo $setpath; ?>?page=getnzb&amp;messageid=<?php echo $spot['messageid']; ?>' target="_blank" title=''>Download NZB</a> </td> </tr>

**Comment by ckruijntjens** [comment]
Hi sweepr

I can see the change also in my spotweb/templates/mobile/spotinfo.inc.php

However the loading icon is still circling and circling. The nzb is not send to sabnzbd. The normal template is working fine however.

Chris kruijntjens.

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: woensdag 4 maart 2015 13:40
Aan: Spotweb/Spotweb
CC: ckruijntjens
Onderwerp: Re: [Spotweb] NZB handling error with mobile template (#37)

https://github.com/Spotweb/Spotweb/blob/master/templates/mobile/spotinfo.inc.php

That's weird, if i look here at line 18 and 52, the change's exist.

Line 18:

**Comment by Sweepr** [comment]
Which mobike platfrom do you use?

Ive only tested this on Android.. you could clear the cache of your browser and or try another browser like firefox or such.?

**Comment by ckruijntjens** [comment]
Hi sweepr,

I have an iphone. I use ios.

Van: Sweepr [mailto:notifications@github.com] 
Verzonden: woensdag 4 maart 2015 14:18
Aan: Spotweb/Spotweb
CC: ckruijntjens
Onderwerp: Re: [Spotweb] NZB handling error with mobile template (#37)

Which mobike platfrom do you use?

Ive only tested this on Android.. you could clear the cache of your browser and or try another browser like firefox or such.?

**Comment by Sweepr** [comment]
@ckruijntjens 
Looks like iOS by standard does not know what to do with *.nzb's,

I've tested the download option's in safari on a borrowed Iphone and the download failed saying that "Safari, the file can not be downloaded" on that Iphone, so this problem now only seems to focus on iOS because it does not know what to do with this file, but i'm not seeing the loading image on my phone's

You could try this: https://itunes.apple.com/us/app/nzb-for-ios/id597832369?mt=8

**Comment by ckruijntjens** [comment]
Hi sweepr,

I dong understanding before iT always worked. You press save in the mobile template and the template push the nzb to Sabnzbd. However heer is a screenshot of the mobile template with the loading image.

Verstuurd vanaf mijn iPhone

> Op 4 mrt. 2015 om 16:34 heeft Sweepr <notifications@github.com> het volgende geschreven:
> 
> @ckruijntjens 
> Looks like iOS by standard does not know what to do with *.nzb's,
> 
> I've tested the download option's in safari on a borrowed Iphone and the download failed saying that "Safari, the file can not be downloaded" on that Iphone, so this problem now only seems to focus on iOS because it does not know what to do with this file, but i'm not seeing the loading image on my phone's
> 
> You could try this: https://itunes.apple.com/us/app/nzb-for-ios/id597832369?mt=8
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<<image2.jpeg>>

**Comment by Sweepr** [comment]
Could be an update that broke it, or something else.. did you try on a different device like Android ? or Ipad maybe?

**Comment by ckruijntjens** [comment]
Hi sweepr,

No but the isseu with the mobile template is in spotweb for about a year normal you can say in the mobile. Template save then iT Will load the nzb to Sabnzbd. Ios is not the problem. IT is a problem in the mobile template.

Verstuurd vanaf mijn iPhone

**Comment by Sweepr** [comment]
Yes, i know.. downloads are working e.g. i can save the file and forward it to SabNZBd on my android, so why not on Iphone's or Ipad's, very strange.

Look like iOS is doing something else, but i have no idea what, i'm going take a look if i can figure out what is going wrong on iOS platform.

**Comment by dsadsdadsadsadsds** [comment]
@Sweepr  - a workaround might be to enable 'zipping' of the NZB files, as this will force Spotweb to always send a zip file with the NZB in it. Sabnzbd can read NZB files just fine from a ZIP file, so it should just work.

Wrt the mobile template - it is a very nice template, but it was never maintained in the official Spotweb repository and actually removed in the 'mediainfo' branch from last year, so it is easy to imagine it will be difficult getting this to work.

**Comment by bakman2** [comment]
As I was the original developer of the mobile template, it has bothered me for a while that the mobile template no longer works, but I have a "temp" fix, that makes it possible to send nzb's directly to sabnzbd/nzbget (saving in blackhole I have not tested). 

modify the following in templates/mobile/spotinfo.inc.php:

       <div data-role="page" id="spots">
        <div data-role="header" data-backbtn="false">
        <h1>Spot info</h1>
<?php if (!empty($spot['sabnzbdurl'])) { ?>
<script type="text/javascript">
$("#loadnzb").on( "click", function(e) {
$("#loadnzb .ui-btn-text").text("WAIT...")

e.preventDefault()
e.stopPropagation()

$.ajax({
type: "GET",
url: $(this).attr('href'),
cache: false,
success: onSuccess
});
function onSuccess(data)
{
$("#loadnzb .ui-btn-text").text("DONE!")
}

})
</script>

<a href="<?php echo $spot['sabnzbdurl']; ?>" id="loadnzb"   data-transition='fade' data-rel="dialog" data-icon="plus" class="ui-btn-right">SAVE</a></th>

**Comment by ckruijntjens** [comment]
Hi bakman,

Wil there also be a permanent fix in the future?

Chris

Verstuurd vanaf mijn iPhone

**Comment by bakman2** [comment]
if spotweb can update the code, it will be permanent.

**Comment by ckruijntjens** [comment]
Hi Bakman,

Will the template work in the future as it dit in the past? I really like the template.

Van: bakman2 [mailto:notifications@github.com] 
Verzonden: woensdag 3 juni 2015 7:46
Aan: spotweb/spotweb
CC: ckruijntjens
Onderwerp: Re: [spotweb] NZB handling error with mobile template (#37)

if spotweb can update the code, it will be permanent.

**Comment by Sweepr** [comment]
Looks nice but i have a few questions, 

How does this SabNZBd function work? for this to work you must login using the mobile template,. otherwise SabNZBd does not know where to send the NZB to using your API key, 

Using the current setup this can only work on private setups, public or shared can't have this SabNZBd function in the mobile template unless you can login and use your own settings, if not strangers will be able to send NZB's to whatever the admin has setup as SabNZBd target, this could be a security risk.

You must use your own credentials/settings so Spotweb knows which SabNZBd server to send the NZB to.

**Comment by bakman2** [comment]
That is correct, you have to login, which is possible in the template.

**Comment by Sweepr** [comment]
I have seen this in the code, but in the recent code the login/logout button's are not active/working

**Comment by Sweepr** [comment]
Maybe @muis or @drazix could add @bakman2 as a member so he can work on the code again?

**Comment by bakman2** [comment]
ok i see the login issue. perhaps I can use we1rdo's spotinfo.inc.php as a basis and convert it to the mobile template.

**Comment by mesa57** [comment]
@bakman2 : did you resolve this issue ?

**Comment by mesa57** [comment]
Solved in pull request #521
