### ISSUE TITLE
Green arrow gone

### ISSUE THREAD

**Issue by mcwieger** [spotweb/spotweb#415]
After some PHP issues on Synology (but no apparent changes), the green download arrow (integration with download client) is gone from the screen. How is this controlled, since I turned the application up and down to get it back?

**Comment by mesa57** [comment]
Depends on you're nzb handling setting. But it should check if sabnzbd/nzbget is available.

**Comment by baruser123** [comment]
> 
> 
> After some PHP issues on Synology (but no apparent changes), the green download arrow (integration with download client) is gone from the screen. How is this controlled, since I turned the application up and down to get it back?

like mesa57 says, are the settings for nzb handling correct. but 2 weeks ago i had a package update from php on my synology, maybe this caused your issues? after this i had a problem that i still saw the posts, but it wasnt possible to retrieve new posts. got a sql error sqlstate No such file or directory when i did a commando line retrieve.php from spotweb. 

after some searching it appears that a value in php,ini must be changed after this php update. the pdo_mysql.default_socket value was wrong. this was pdo_mysql.default_socket=/tmp/mysqld.sock and must be changed to pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock

this value i read from my.cnf and command mysql> show variables like '%sock%', i got this info from https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

dont know if this is a reason for your issue, but because you said synology and php issue, first thing i thought about this

**Comment by mcwieger** [comment]
Updated the nzbget handling settings (although had not changed those) and it's working again. Thanks!
