### ISSUE TITLE
Spotweb can't find NZB, better error handling

### ISSUE THREAD

**Issue by kooimens** [spotweb/spotweb#50]
When spotweb tries to find an NZB belonging to a certain a spot, it sometimes can't find the NZB anymore. This usually occurs with older spots (> 1200 days?).

If I download the NZB manually I receive the following error:
`getBody(): Failed to retrieve article:  {"result":"failure","data":[],"info":[],"warnings":[],"errors":["No such article found [response: \"no such article\"]"]}`
Sending the NZB to sabnzbd is stuck with the download button haning on the "loading, sending nzb to sab" icon. 

Is there a way to do a check and remove this spots automatically? This is really annoying because sickrage thinks it snatched an episode, but sabnzbd do not received anything and sickrage is therefore stuck a status `snatched`

**Comment by Sweepr** [comment]
I don't know how large the retention is for the Usenetprovider you use.. if it is indeed 1200 day's then everything that is kept beyond that time by spotweb itself is no longer available by your provider.

What you could do is lower the retention in spotweb settings.

Settings -> Retrieve -> Retention on spots (in days). Older spots will be erased. Select 0 to keep all spots.

Set to 1000 day's for example (depending on the usenet server retention ofcourse)

**Comment by kooimens** [comment]
I think it's not usenet server retention related. For example, I can't even download the spot:
`Strike Back S03E10 720p HDTV x264 EVOLVE`

This spot is 2 years and 4 months old. Probably a take down?

**Comment by Sweepr** [comment]
I tried to download this particular spot, and it was succesfull on my end.

Could you please verify the NZB with the one i have?

http://pastebin.com/yi3bQ6ZE

**Comment by kooimens** [comment]
That's weird. It seems to be the same NZB. The spotter is zoutoplossing. When is use the searchengine link i get four hits:
![1](https://cloud.githubusercontent.com/assets/3150962/6601558/a3017eb8-c816-11e4-83f0-de4dad5cc509.jpg)

**Comment by Sweepr** [comment]
If you try to download this NZB now?  does it still fail?

**Comment by kooimens** [comment]
You mean download it the way it failed before? Yeah, still failing...
I found this public spotweb site when googling my error:
`http://dl.d1rk.nl:9095/`  (dunno, if it's allowed here anyway)

But, if I look for the spot on this website, the same error comes up as on my installation.

**Comment by Wally73** [comment]
i have the spot also. I can download the nzb just fine but the rest of it
is dcma'd so no use

**Comment by kooimens** [comment]
Ok. If I use http://www.schaatsbergen.com/spotweb I can download the NZB as well. Don't know why my installation isn't able to retrieve the NZB?

**Comment by Wally73** [comment]
to be able to download an nzb the USP from the spotweb instance must be
able to find it so i assume yours can't find it

**Comment by Sweepr** [comment]
@Wally73,. that's what i thought in my first reply to this question.. 

@kooimens, which USP does your spotweb installation use?

**Comment by kooimens** [comment]
supernews EU

**Comment by Sweepr** [comment]
@kooimens

Could be that this: http://dl.d1rk.nl:9095/ uses an USP that is on the same cluster as Supernews, 

On the supernews website they advertise with:

Multiple Copies Ensure 100% Completion and 2357 Days Binary Retention

We keep multiple copies of every Usenet article to ensure a 100% article completion rate. This means you never experience downtime or missing articles. Unlike other Usenet providers, Supernews makes all articles available at unlimited speeds - regardless of the age of the article.

Now we have just disproved that statement..
Think you could contact Supernews and ask for clarification.

**Comment by kooimens** [comment]
Thanks. I've sent them an email and this topic as reference.

**Comment by kooimens** [comment]
What is the best way to point my USP to the NZB that's unfindable?

**Comment by Sweepr** [comment]
Using binsearch.i.n.f.o. or nzbindex.c.o.m

**Comment by Sweepr** [comment]
Did you receive any response yet?

**Comment by kooimens** [comment]
Yeah. But I was a little late with my answer to their response;). They were fast the first time so i'm expecting an answer within 48 hours.

One more example:
![1](https://cloud.githubusercontent.com/assets/3150962/6695797/402609da-cce4-11e4-9df2-8d3edf34c5c9.jpg)
This one isn't findable with my USP. It is also not findable with binsearch, nzbindex or some other public newznab sites. It looks like it's completely gone, somehow. Shouldn't be there any build-in checks to auto remove such spots? Right now, nothing is send to my nzb-downloader if sickbeard/couchpotato finds such a spot. They both found the spot and set the episode/movie to snatched.

**Comment by Sweepr** [comment]
Any update?

**Comment by Sweepr** [comment]
No update in 2 weeks, assume issue resolved.

**Comment by Ravefiend** [comment]
The same error comes us from retrieve.php so a better handling of this could be of use.

Usenet server: news.eu.supernews.com 119 (due to issue #65)
Retention on spots: 0 (all spots)
Retrieve full spots: [checked]
Prefetch images: [unchecked]
Prefetch NZB files: [checked]
Retrieve comments: [checked]
Retrieve full comments: [checked]
Retrieve reports [checked]

Messages like:

getBody(): Failed to retrieve article: <f60445fa66374257a77c8d9b509cb94328@spot.net>

getBody(): Failed to retrieve article: <b02d38bb579a41ba9d8faeca88b218c033@spot.net>

It does appear to be related to Supernews itself as these articles do exist on e.g. Astraweb.

===== Supernews: missing articles =======
Looking up host 'news.eu.supernews.com'...
Host 'news.eu.supernews.com' resolved to 138.199.68.130.
Connecting to 138.199.68.130:23...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.
200 Supernews server ready
g6j33jggFyb7QsBErxuuOf4j4g24pQpjCzfHeRiifm2HrTwYQq
500 syntax error or unknown command
AUTHINFO USER ............
381 more authentication required
AUTHINFO PASS ............
281 Supernews server ready
HEAD <f60445fa66374257a77c8d9b509cb94328@spot.net>
430 no such article
HEAD <b02d38bb579a41ba9d8faeca88b218c033@spot.net>
430 no such article

====== Astraweb: articles found ========
Looking up host 'news.astraweb.com'...
Host 'news.astraweb.com' resolved to 207.246.207.110.
Connecting to 207.246.207.110:119...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.
200 news.astraweb.com NNRP Service Ready (posting ok) (yEnc enabled).
AUTHINFO USER .............
381 PASS required
AUTHINFO PASS .............
281 Ok
HEAD <f60445fa66374257a77c8d9b509cb94328@spot.net>
221 0 <f60445fa66374257a77c8d9b509cb94328@spot.net> head
Path: news.astraweb.com!border6.newsrouter.astraweb.com!not-for-mail
From: xxxwebwatchers <xxxwebwatchers@spot.net>
Subject: c5ad16b2574f435a81a1636ede60adde
Newsgroups: alt.binaries.ftd
Message-ID: <f60445fa66374257a77c8d9b509cb94328@spot.net>
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8bit
Date: 12 Mar 2011 12:41:25 GMT
Lines: 225
Organization: Unlimited download news at news.astraweb.com
NNTP-Posting-Host: a3406fac.news.astraweb.com
X-Trace: DXC=D5`e1QRX08JRm_f?\>0G3FL?0kYOcDh@JcWP9noWa<nBXUI8bb:A\1OdbVXah0T`5BFK_@ncK<YQMkG85QX15ALIK^`CA[TSBHMPofg2iD53F@
.
HEAD <f60445fa66374257a77c8d9b509cb94328@spot.net>
221 0 <f60445fa66374257a77c8d9b509cb94328@spot.net> head
Path: news.astraweb.com!border6.newsrouter.astraweb.com!not-for-mail
From: xxxwebwatchers <xxxwebwatchers@spot.net>
Subject: c5ad16b2574f435a81a1636ede60adde
Newsgroups: alt.binaries.ftd
Message-ID: <f60445fa66374257a77c8d9b509cb94328@spot.net>
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8bit
Date: 12 Mar 2011 12:41:25 GMT
Lines: 225
Organization: Unlimited download news at news.astraweb.com
NNTP-Posting-Host: a3406fac.news.astraweb.com
X-Trace: DXC=D5`e1QRX08JRm_f?\>0G3FL?0kYOcDh@JcWP9noWa<nBXUI8bb:A\1OdbVXah0T`5BFK_@ncK<YQMkG85QX15ALIK^`CA[TSBHMPofg2iD53F@

Yes these are old spots, but interestingly enough they are available via Astraweb. 

Would these missing spots be picked doing the following:
1. Let the current retrieval via Supernews complete
2. Change the configuration to Astraweb
3. Run a retrieve.php -retro 

Is that considered safe and will it pick up these missed articles?

**Comment by Sweepr** [comment]
I would not recommend changing usenetservers in between or risk database corruption.
This can cause alot of problems, best is to stick with one USP server with decent retention and stay there.

**Comment by Wally73** [comment]
message id's are NOT the same on every USP so if you switch it brings a
crapload of problems with your existing spots
