### ISSUE TITLE
Spotweb crashes after latest updates to php files

### ISSUE THREAD

**Issue by sjakief** [spotweb/spotweb#652]
On Sunday 17th of january, there have been some updates which cause the error message below, when running git pull

There have SpotWeb v0.68.32.33 on PHP v7.2.34 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

#0 /var/www/html/spotweb/lib/dbeng/dbeng_pdo.php(86): dbeng_pdo->exec('DELETE FROM com...', Array)
#1 /var/www/html/spotweb/lib/dao/Base/Dao_Base_Comment.php(305): dbeng_pdo->modify('DELETE FROM com...')
#2 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(636): Dao_Base_Comment->removeComments(Array)
#3 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process(Array, '3485018', 3485124, 1610976605.3197)
#4 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd(3485124, '5000')
#5 /var/www/html/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
#6 {main}**Describe the bug/issue**
 - A clear and concise description of what the bug is.

**To Reproduce**
1.  start commandshell , run command 'git pull'

**Expected behavior**
I was expecting the following message: '**Already up-to-date**.'

**Screenshots**
see error mesaage

**Desktop (please complete the following information):**
 - OS: [Windows 10 version 2004 OS build 19041.685]
 - Browser [mozilla firefox]
 - Spotweb Version [v0.68.32.33]
 - Which branch  (Develop)
 -  PHP version PHP v7.2.34
 -  Device information (Virtual machine Centos 7)

**Comment by mesa57** [comment]
Please update from the develop branch.
Related to #645

**Comment by sjakief** [comment]
I am a complete NOOB with this, so I didn't understand.... I  executed the command php upgrade-db --reset-db and now I am retrieving all again, but I don't know if that is what you meant?

**Comment by sjakief** [comment]
After about 2 hours filling the database, I received the error message again
extra info Ver 15.1 Distrib 5.5.68-MariaDB,

**Comment by mesa57** [comment]
It probably means you have to reinstall spotweb from the DEVELOP branch

**Comment by sjakief** [comment]
I removed complete spotweb directory, I did a reset of the database, cloned a new develop tree in a new spotweb directory, copied db.settings.inc file, copied ownsettings.php file, started php retrieve.php, this is the error message again...
Retrieving 2753752 till 2754753 (parsed: 4, in DB: 997, signed: 0, invalid: 2, rtntn.skip: 0, mod: 2, full: 0, total: 1001)

after this, I cannot start retrieve.php anymore.

**Comment by mesa57** [comment]
@Sweepr can you help ?

**Comment by Sweepr** [comment]
@sjakief.

Does it help if you disable retrieval of comments at first?
So initial retrieve without pulling comments?

Then enable comments after retrieve has finished first run?

**Comment by Sweepr** [comment]
So do: `php upgrade-db --reset-db` then:

Make sure the setttings are no set,

![image](https://user-images.githubusercontent.com/2857865/104962863-9e16c600-59d9-11eb-8566-0f20cebc1016.png)

![image](https://user-images.githubusercontent.com/2857865/104962918-c0a8df00-59d9-11eb-968c-190c31bd8840.png)

Run `php retrieve.php`

**Comment by Sweepr** [comment]
@sjakief 
Fyi,
I just did a `git pull` to get the latest develop branch with all new changes made yesterday, i ran retrieve.php on PHP 7.4.14 on CentOS. here it run's fine with or without comments / reports retrieval.

**Comment by sjakief** [comment]
the handling of moderation messages was set to 'do nothing' now, de rest of the options were already right, now I can run php retrieve again. Thanks for that. 
But can you tell me why this is happening?  it all worked for a long time, and suddenly it goes to....you know ;-)

**Comment by mesa57** [comment]
Are you perhaps using usenet provider sunnyusenet ?

**Comment by mesa57** [comment]
@Sweepr I can confirm that the issue still exists when setting moderate spots to be deleted.

**Comment by Sweepr** [comment]
@mesa57 I am not seeing this or able to reproduce when set "Delete moderated spots" is this USP depending maybe?

Think the problem resides in this line:       ` if (isset($msgIdList) && $msgIdList !== '') `

https://github.com/spotweb/spotweb/blob/de85e42978c29be167447acb4d8434a19cf894e9/lib/dao/Base/Dao_Base_Comment.php#L304

Better would be this:

        `if (isset($msgIdList) && !empty($msgIdList)) {`

function empty($var) bool
Determine whether a variable is considered to be empty. A variable is considered empty if it does not exist or if its value equals FALSE. empty() does not generate a warning if the variable does not exist.
Parameters:
mixed
$var
Variable to be checked.
Note: Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.
No warning is generated if the variable does not exist. That means empty() is essentially the concise equivalent to !isset($var) || $var == false.
Returns:
FALSE if var exists and has a non-empty, non-zero value. Otherwise returns TRUE.
The following things are considered to be empty:
"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
$var; (a variable declared, but without a value)

Could you check if this finally fixes this issue?

I will make a PR for this.

**Comment by Sweepr** [comment]
@mesa57

I was able to reproduce this now when i emptied the `moderatedringbuffer` table, then set "Delete moderated spots" and did a `php retrieve.php --retro` 

After i was able to reproduce this i put this fix in place and was able to continue `retrieve.php` without seeing this issue.

**Comment by muis** [comment]
I copied that line to many other places in #650 so in that case they all need to be replaced.
