### ISSUE TITLE
Fatal error occured during retrieve: Bootstrap.php(68): Bootstrap->validate(Object(Services_Settings_base))

### ISSUE THREAD

**Issue by jeroenbeuz** [spotweb/spotweb#800]
**Describe the bug/issue**
 - After a fresh install of the DEV branch on Windows with XAMPP I'm not able to run retrieve.php with success. Not in the spotweb ui nor in the command line.

**Have you searched the internet or Github for an answer?**
 - Yes, for a couple of hours but did not find anything similar to my issue

**To Reproduce**
1. Freshly install XAMPP and the DEV branch
2. Run the install.php and validate the news server
3. Run retrieve in either ui or command line
4. See error in command line (not in ui, the ui just shows 'Laatste update: onbekende' after 1 second)

**Expected behavior**
 - I'd expect spots to load

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Spotweb Version: 1.5.4
 - Which branch: Develop
 -  PHP version: 8.2.0
 -  Device information: N/A

**Additional context**
In the first install page everything is OK except for: zip, PostgresSQL and Own settings file
In the news server page I've verified my news server credentials
Changing to not using SSL (119) also does not work, same error when retrieving spots
Also tried the master branch but with the same results
I do see a deprecation warning in the install screen: 'Deprecated: Function utf8_encode() is deprecated in C:\xampp\htdocs\spotweb\vendor\szymach\c-pchart\constants.php on line 48'
The error in the command line:
![image](https://user-images.githubusercontent.com/23665003/211474286-5541898d-c9ad-44b3-b88d-174ef42eb1d0.png)

**Comment by Sweepr** [comment]
I'd suggest to run on PHP 8.1 for now..  pchart does not support 8.2 yet so it seems, this is beyond our scope.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jeroen Beuzenberg ***@***.***>
Sent: Tuesday, January 10, 2023 7:08:31 AM
To: spotweb/spotweb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotweb/spotweb] Fatal error occured during retrieve: Bootstrap.php(68): Bootstrap->validate(Object(Services_Settings_base)) (Issue #800)


Describe the bug/issue

  *   After a fresh install of the DEV branch on Windows with XAMPP I'm not able to run retrieve.php with success. Not in the spotweb ui nor in the command line.

Have you searched the internet or Github for an answer?

  *   Yes, for a couple of hours but did not find anything similar to my issue

To Reproduce
Steps to reproduce the behavior:

  1.  Freshly install XAMPP and the DEV branch
  2.  Run the install.php and validate the news server
  3.  Run retrieve in either ui or command line
  4.  See error in command line (not in ui, the ui just shows 'Laatste update: onbekende' after 1 second)

Expected behavior

  *   I'd expect spots to load

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   OS: Windows 11
  *   Browser: Chrome
  *   Spotweb Version: 1.5.4
  *   Which branch: Develop
  *   PHP version: 8.2.0
  *   Device information: N/A

Additional context
In the first install page everything is OK except for: zip, PostgresSQL and Own settings file
In the news server page I've verified my news server credentials
Changing to not using SSL (119) also does not work, same error when retrieving spots
Also tried the master branch but with the same results
I do see a deprecation warning in the install screen: 'Deprecated: Function utf8_encode() is deprecated in C:\xampp\htdocs\spotweb\vendor\szymach\c-pchart\constants.php on line 48'
The error in the command line:
[image]<https://user-images.githubusercontent.com/23665003/211474286-5541898d-c9ad-44b3-b88d-174ef42eb1d0.png>

**Comment by Sweepr** [comment]
If you can, please open an issue on their page: https://github.com/szymach/c-pchart

It says on their repo:

"Support for PHP versions from 5.4 to 8.1."

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeroenbeuz** [comment]
Thanks for the quick answer, I'll downgrade to 8.1 for now. Can the wiki be updated to reflect this version requirement of XAMPP/PHP? Here it is: https://github.com/spotweb/spotweb/wiki/Spotweb---Windows-(English)

**Comment by jeroenbeuz** [comment]
Fixed by downgrading to PHP 8.1

**Comment by Sweepr** [comment]
Question, do you know which version of [szymach/](https://packagist.org/packages/szymach/)c-pchart was installed for PHP 8.2? 

The original error reported states: `'Deprecated: Function utf8_encode() is deprecated in C:\xampp\htdocs\spotweb\vendor\szymach\c-pchart\constants.php on line 48'` but this should have been fixed in https://packagist.org/packages/szymach/c-pchart#v3.0.16  see: https://github.com/szymach/c-pchart/releases/tag/v3.0.16
