### ISSUE TITLE
possible memory leak in openssl code

### ISSUE THREAD

**Issue by xpunkt** [spotweb/spotweb#804]
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 335544320 bytes) in /var/www/localhost/htdocs/spotweb/lib/services/Signing/Services_Signing_Openssl.php on line 38

**Comment by Sweepr** [comment]
We need more information, fill in the template:

**Describe the bug/issue**
 - A clear and concise description of what the bug is.

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
 -  PHP version
 -  Device information (ReadyNAS/Synology/FreeNAS)

**Smartphone if applicable (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
-  PHP version
-  Device information (ReadyNAS/Synology/FreeNAS)

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by Sweepr** [comment]
No response, closing. reply to this if you still have problems.
