### ISSUE TITLE
Spotweb times-out when using the search bar or using Interactive Search in Sonarr

### ISSUE THREAD

**Issue by moostmartijn** [spotweb/spotweb#808]
**Describe the bug/issue**
Spotweb times-out when using the search bar within Spotweb or using Interactive Search in Sonarr.

Half of the times Spotweb times-out (or takes a really long time) when I use the search bar within Spotweb or when I use the interactive search in Sonarr or Radarr. 

**I do have the feeling it times-out the first time that day I use the search bar / interactive search. It will time out, but 5 minutes later I try to reproduce and it will work flawless. And like 15 minutes later the issue reoccurs...** 

**Have you searched the internet or Github for an answer?**
Yes, I did not find a similar problem/solution. 

I did open the same issue a few weeks ago, but in the end the given solution did not work. 

**To Reproduce**
1. Go to Spotweb
2. Search for a movie

This will result in long waiting times

1. Go to Sonarr
2. Use interactive search to search for a season
3. Indexer Spotweb will time-out

**Expected behavior**
The expected behavior will give results within 10 seconds. 

**Screenshots**
<img width="1081" alt="Schermafbeelding 2023-02-26 om 12 19 45" src="https://user-images.githubusercontent.com/31592734/221407511-d5fe468a-e257-4a89-9ce1-c2d657282792.png">
Search screen will be there for 90 seconds or so and returns all the results, excepts the results from Spotweb

<img width="370" alt="Schermafbeelding 2023-02-26 om 12 20 41" src="https://user-images.githubusercontent.com/31592734/221407550-a4307e5d-e4bb-498a-9319-a09daf2a7511.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Linux
 - Browser [e.g. chrome, safari]: Chrome
 - Spotweb Version [e.g. 1.4.8]: Latest (can't find the version anywhere...)
 - Which branch  (Master/Develop): Master
 -  PHP version: PHP 7.4
 -  Device information (ReadyNAS/Synology/FreeNAS): Synology NAS with webserver, appache 2.4

**Additional context**
Logs from Sonarr:
```
2023-02-26 12:19:30.0|Warn|Newznab|Spotweb server is currently unavailable. http://localhost/spotweb/api?t=tvsearch&cat=5010,5020,5030,5040,5045,5050,5080&extended=1&apikey=(removed)&offset=0&limit=100&rid=29741&tvmazeid=1437&season=2 The operation has timed out.: 'http://localhost/spotweb/api?t=tvsearch&cat=5010,5020,5030,5040,5045,5050,5080&extended=1&apikey=(removed)&offset=0&limit=100&rid=29741&tvmazeid=1437&season=2'
```

**There are no logs from Spotweb itself?**

**Comment by Sweepr** [comment]
You should check the timeout settings in php.ini

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
From: moostmartijn ***@***.***>
Sent: Sunday, February 26, 2023 12:25:27 PM
To: spotweb/spotweb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotweb/spotweb] Spotweb times-out when using the search bar or using Interactive Search in Sonarr (Issue #808)


Describe the bug/issue
Spotweb times-out when using the search bar within Spotweb or using Interactive Search in Sonarr.

Half of the times Spotweb times-out (or takes a really long time) when I use the search bar within Spotweb or when I use the interactive search in Sonarr or Radarr.

I do have the feeling it times-out the first time that day I use the search bar / interactive search. It will time out, but 5 minutes later I try to reproduce and it will work flawless. And like 15 minutes later the issue reoccurs...

Have you searched the internet or Github for an answer?
Yes, I did not find a similar problem/solution.

I did open the same issue a few weeks ago, but in the end the given solution did not work.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to Spotweb
  2.  Search for a movie

This will result in long waiting times

  1.  Go to Sonarr
  2.  Use interactive search to search for a season
  3.  Indexer Spotweb will time-out

Expected behavior
The expected behavior will give results within 10 seconds.

Screenshots
[Schermafbeelding 2023-02-26 om 12 19 45]<https://user-images.githubusercontent.com/31592734/221407511-d5fe468a-e257-4a89-9ce1-c2d657282792.png>
Search screen will be there for 90 seconds or so and returns all the results, excepts the results from Spotweb

[Schermafbeelding 2023-02-26 om 12 20 41]<https://user-images.githubusercontent.com/31592734/221407550-a4307e5d-e4bb-498a-9319-a09daf2a7511.png>

Desktop (please complete the following information):

  *   OS: [e.g. iOS]: Linux
  *   Browser [e.g. chrome, safari]: Chrome
  *   Spotweb Version [e.g. 1.4.8]: Latest (can't find the version anywhere...)
  *   Which branch (Master/Develop): Master
  *   PHP version: PHP 7.4
  *   Device information (ReadyNAS/Synology/FreeNAS): Synology NAS with webserver, appache 2.4

Additional context
Logs from Sonarr:

2023-02-26 12:19:30.0|Warn|Newznab|Spotweb server is currently unavailable. http://localhost/spotweb/api?t=tvsearch&cat=5010,5020,5030,5040,5045,5050,5080&extended=1&apikey=(removed)&offset=0&limit=100&rid=29741&tvmazeid=1437&season=2 The operation has timed out.: 'http://localhost/spotweb/api?t=tvsearch&cat=5010,5020,5030,5040,5045,5050,5080&extended=1&apikey=(removed)&offset=0&limit=100&rid=29741&tvmazeid=1437&season=2'


There are no logs from Spotweb itself?

**Comment by Sweepr** [comment]
https://stackoverflow.com/questions/3829403/how-to-increase-the-execution-timeout-in-php

**Comment by moostmartijn** [comment]
Thanks for the replies. I changed the 'default_socket_timeout' from 60 to 180. I will do some further testing the coming days and I hope the issue will not return. Will 180 seconds be enough? ;)

**Comment by Sweepr** [comment]
> default_socket_timeout

It all depends on the capabilities of your NAS, be sure to also check for "max_execution_time"  most of the time it's wise to check the PHP error_log's for anything that point to the issue, probably it PHP/Apache or in some cases SQL settings are causing this issue.

**Comment by moostmartijn** [comment]
'max_execution_time' is 240. Maybe my NAS has limited capabilities. I will also try to add Spotweb to my NUC. I will close this issue for now and will re-open if the issue still occurs. Thanks for the help!
