### ISSUE TITLE
Undefined array key "enc"Undefined array key "port" 

### ISSUE THREAD

**Issue by Radiotechniman** [spotweb/spotweb#832]
**Describe the bug/issue**
When installing a new instance of spotweb you set a new custom news server and when you click "verify usenet server" this error pops up,
below the error there is a red area which states : 
A server portnumber has to be entered [response: ""]
Please correct the errors in below form and try again 

The issue seems to be related to the fact there is no port information filled in, nor is there a field to enter the data.

**Expected behavior**
Either the form should default the port number to 119 or better yet a place to enter the port number for the custom news server

**Screenshots**
![Screenshot 2023-10-01 205320](https://github.com/spotweb/spotweb/assets/3715085/6a68a28e-654b-4b96-b559-50d1c8b26b7a)

*Additional context**
None at the moment

**Comment by Sweepr** [comment]
You can also skip validation amd enter this in settings later.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Radiotechniman ***@***.***>
Sent: Sunday, October 1, 2023 8:55:46 PM
To: spotweb/spotweb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotweb/spotweb] Undefined array key "enc"Undefined array key "port" (Issue #832)


Describe the bug/issue
When installing a new instance of spotweb you set a new custom news server and when you click "test connection" this error pops up,
below the error there is a red area which states :
A server portnumber has to be entered [response: ""]
Please correct the errors in below form and try again

The issue seems to be related to the fact there is no port information filled in, nor is there a field to enter the data.

Expected behavior
Either the form should default the port number to 119 or better yet a place to enter the port number for the custom news server

Screenshots
[Screenshot 2023-10-01 205320]<https://user-images.githubusercontent.com/3715085/271847833-6a68a28e-654b-4b96-b559-50d1c8b26b7a.png>

Additional context*
None at the moment

**Comment by Radiotechniman** [comment]
I know, tried this too, but for some reason nothing is being populated, I was hoping this part would be working so I can validate the connection is OK. 

But, if you have this functionality in your application it should be working... right?

**Comment by nismanoku** [comment]
Behind your server name can you specify :563 or :443. Should normally work
